variable "env" {}
variable "subnet_ids" {}
variable "allow_cidr_blocks" {}
variable "vpc_id" {}
variable "num_cache_nodes" {}
variable "node_type" {}
variable "replicas_per_node_group" {}
variable "engine" {}
variable "engine_version" {}
